# Generated by Django 4.2.1 on 2023-06-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_rename_from_user_incomingfriendrequest_from_whom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='outgoing_friend_requests',
        ),
        migrations.DeleteModel(
            name='OutgoingFriendRequest',
        ),
    ]
