# Generated by Django 4.2.1 on 2023-06-10 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_remove_user_outgoing_friend_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='incoming_friend_requests',
            field=models.ManyToManyField(related_name='Заявки', through='friend.IncomingFriendRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
