# Generated by Django 4.2.1 on 2023-06-10 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_alter_user_incoming_friend_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomingFriendRequest',
            new_name='FriendRequest',
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='incoming_friend_requests',
        ),
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(related_name='Заявки', through='friend.FriendRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
